### ISSUE TITLE
Chrome issue - angular-deckgrid: No CSS configuration found 

### ISSUE THREAD

**Issue by mkoldobsky** [akoenig/angular-deckgrid#14]
I am getting this issue on Chrome (not on Firefox) even you demo site is not working. A few days ago it use to work.
Chrome Version 34.0.1797.2 dev-m

**Comment by feus4177** [comment]
When I ran into this error it was because we didn't have our CSS/HTML configured correctly. The solution was to have `<div deckgrid ...>` in the HTML and the CSS selectors configured like `.deckgrid[deckgrid]...`.  In the deckgrid source there is a regex that expects this CSS selector.

**Comment by Nicolazinho** [comment]
On the Ionic platform I still experienced the problem @exentrich mentioned [earlier](https://github.com/akoenig/angular-deckgrid/issues/14#issuecomment-35728861).

Replacing `visibility: hidden;` with `display: none;` resolved it for me.

**Comment by srameshr** [comment]
Tried replacing `visibility: hidden;` with `display: none;`.
It does not work.
