### ISSUE TITLE
ngClick doesn't work inside templates

### ISSUE THREAD

**Issue by jvgeee** [akoenig/angular-deckgrid#3]
Here's a plunker with a test: http://plnkr.co/edit/DWj896iIY1TGW5XAqfnW?p=preview

As you can see, calling `ng-click` on an element inside of a template doesn't work correctly. In the example above, nothing is written to console nor is printed in `$scope.message`.

**Comment by jcirionotero** [comment]
Hola @akoenig, i use deckgrid, but doesn't work, none click in template. Any idea?

Ex: <a ng-click="alert($index)">Más información</a> // nothing !!!
