### ISSUE TITLE
Support for Angular 1.3 would be awesome :)

### ISSUE THREAD

**Issue by hacker112** [akoenig/angular-deckgrid#64]
Could maybe be as easy as changing the version in bower.json:

```
  "dependencies": {
    "angular": "~1.2.0"
  },
```

**Comment by hacker112** [comment]
Support for 1.4 and soon 1.5 support would be nice. I guess that it is the same procedure.
Changing the version requirement to "^1.3" would include all newer 1.x-versions.

**Comment by fastone** [comment]
:+1:
