### ISSUE TITLE
Add class to current selected

### ISSUE THREAD

**Issue by duykhoa87** [akoenig/angular-deckgrid#73]
I want to add class selected to current item that I am choosing. The code is
>     <div class='a-card' data-ng-class="{selected:card.id === selectedIndex}" >
>     <img src="" data-ng-src="{{card.src}}" ng-click="mother.SelectPhoto(card.id)"  >
>     </div>

**Comment by akoenig** [comment]
I would suggest to put a flag on the card object. Something like:

```js
...
$scope.selectPhoto = function selectPhoto (card) {
    // TODO: "unselect all cards"
    card.selected = true;
};
```
HTML:

```html
<div class='a-card' data-ng-class="{selected:card.selected}" >
```
