### ISSUE TITLE
Not working with IE11

### ISSUE THREAD

**Issue by tcdude** [akoenig/angular-deckgrid#87]
I'm not sure if this is a known behavior but it seems that angular-deckgrid doesn't work with Internet Explorer 11.. Neither my implementation nor the demo seem to work and throw the following error: 

*angular-deckgrid: No CSS configuration found (see https://github.com/akoenig/angular-deckgrid#the-grid-configuration)*

It works flawlessly with Firefox and Chrome (tested on Windows/Linux/Android) and on iOS. I'm using v0.5.0

Is there a way to make it work with IE 11? I really like deckgrid and would hate to have to look for an other implementation that supports IE as well...

**Comment by akoenig** [comment]
Duplicate of #86
