### ISSUE TITLE
Critical Issue in IE-11

### ISSUE THREAD

**Issue by Ajianz** [akoenig/angular-deckgrid#89]
The Angular Deckgrid isnt functioning well in IE-11 . It dispalys a blank page 
Its Throwing the below Error in the console:

angular-deckgrid: No CSS configuration found (see https://github.com/akoenig/angular-deckgrid#the-grid-configuration)

It works fine in other browsers. Could you resolve the issue ASAP?

**Comment by akoenig** [comment]
Duplicate of #86
